#define DECLARE_FRAME_ZEPHYR(n) LV_IMG_DECLARE(zephyr_frame_##n)

DECLARE_FRAME_ZEPHYR(000);
DECLARE_FRAME_ZEPHYR(001);
DECLARE_FRAME_ZEPHYR(002);
DECLARE_FRAME_ZEPHYR(003);
DECLARE_FRAME_ZEPHYR(004);
DECLARE_FRAME_ZEPHYR(005);
DECLARE_FRAME_ZEPHYR(006);
DECLARE_FRAME_ZEPHYR(007);
DECLARE_FRAME_ZEPHYR(008);
DECLARE_FRAME_ZEPHYR(009);
DECLARE_FRAME_ZEPHYR(010);
DECLARE_FRAME_ZEPHYR(011);
DECLARE_FRAME_ZEPHYR(012);
DECLARE_FRAME_ZEPHYR(013);
DECLARE_FRAME_ZEPHYR(014);
DECLARE_FRAME_ZEPHYR(015);